-- 11/03/2025

INSERT INTO enfermedades (descripcion) VALUES ('Absceso en cornea'),
('Absceso en glúteo'),
('Absceso periodontal'),
('Accidente cerebrovascular'),
('Aczema de piel en pies'),
('Aislamiento preventivo'),
('Amigdalitis pultácea'),
('Amputación tercer dedo del pie'),
('Amputación tercer dedo del pie derecho'),
('Angina'),
('Angina pultácea'),
('Angioplastía coronaria'),
('Apendicitis aguda / cirugía'),
('Arteriografía de miembros inferiores'),
('Artralgia de tobillo'),
('Astenia y estado febril'),
('Bronco espasmo'),
('Broncoespasmo'),
('Broncopatía'),
('Bronquitis'),
('Bronquitis Aguda'),
('Bronquitis y estado febril'),
('Bronquitis, cuadro febril'),
('Caída de Motocicleta'),
('Caída en baño, traumatismos varios'),
('Cálculos renales'),
('Cefalea tensional'),
('Cefalea tensional/fiebre viral'),
('Cefalea y Cervicalgia'),
('Cervicalgia'),
('Cervicalgia / dolores en cuello y brazo'),
('Cervicalgia /continúa con dolores en cuello y brazo'),
('Cervicalgia y mialgia'),
('Cervicobraquialgia'),
('Cervicodorsalgia'),
('Cifras de Tensión Elevadas'),
('Cirugía de abdomen'),
('Cirugía de cataratas en ambos ojos'),
('Cirugía de cataratas ojo derecho'),
('Cirugía de cataratas ojo izquierdo'),
('Cirugía de Colelitiasis sintomática'),
('Cirugía de fístula perianal'),
('Cirugía de hernia'),
('Cirugía de Hernia inguinal'),
('Cirugía de hernia umbilical'),
('Cirugía de hombro derecho, tendón lesionado'),
('Cirugía de manguito rotador y desgarro'),
('Cirugía de neumotórax espontáneo'),
('Cirugía de Vesícula'),
('Cirugía de vesícula / colesistitis aguda'),
('Cirugía dedo grande del pie'),
('Cirugía en fractura de mano derecha'),
('Cirugía en hombro derecho'),
('Cirugía en vías respiratorias “sinusitis”'),
('Cirugía endoscópica'),
('Cirugia por nódulo en garganta'),
('Cirugía programada / litiasis vesicular'),
('Cirugía urológica'),
('Cirugías de rodilla y tobillo izquierdo'),
('Codo derecho Fisurado'),
('Colangitis'),
('Colecistitis aguda'),
('Colecistitis aguda / piedra en vesícula'),
('Colecistitis aguda / piedras en vesícula'),
('Colecistitis aguda y hernia'),
('Cólico biliar'),
('Cólico renal'),
('Cólicos hepáticos'),
('Cólicos intestinales'),
('Colocación de 2 stent'),
('Congestión nasal y rinitis'),
('Conjuntivitis en ambos ojos'),
('Contacto estrecho Covid 19 Positivo'),
('Contagio de virus Covid 19'),
('Contractura cervicodorsal'),
('Contractura en gluteo izquierdo'),
('Contractura muscular cervicodorsal'),
('Contusión / Desgarro'),
('Contusión en brazo y rostro'),
('Contusión en codo izquierdo'),
('Contusión y corte en dedo pulgar derecho'),
('Contusiones con corte en mano izquierda'),
('Contusiones múltiples / caída de estribo'),
('Contusiones varias'),
('Corte en cuero cabelludo'),
('Corte en palma de mano derecha'),
('Corte en pierna (accidente de tránsito)'),
('Corte y contusión en espalda'),
('Corte y contusión en pierna izquierda'),
('COVID 19 / Enfermedad profesional'),
('Crísis hemorroidal'),
('Crisis Hipertensiva'),
('Cuadro bronquial'),
('Cuadro Clínico de ACV'),
('Cuadro Covid 19 / No está vacunado'),
('Cuadro de alergia'),
('Cuadro de alergia / aislamiento preventivo'),
('Cuadro de Angina'),
('Cuadro de Angustia'),
('Cuadro de artrosis'),
('Cuadro de Bronquitis'),
('Cuadro de bronquitis aguda'),
('Cuadro de Cefalea asociada a Insomnio'),
('Cuadro de Cervicalgia'),
('Cuadro de Cervicalgia, cefaleas y vómitos'),
('Cuadro de Cervicobraquialgia'),
('Cuadro de diverticulitis aguda'),
('Cuadro de Erisipela'),
('Cuadro de estrés agudo'),
('Cuadro de faringitis'),
('Cuadro de gastroentecolitis'),
('Cuadro de Gastroenteritis Aguda'),
('Cuadro de Lumbociatalgia'),
('Cuadro de Neumonitis'),
('Cuadro de odinofagia'),
('Cuadro de parotiditis'),
('Cuadro de Síndrome Depresivo'),
('Cuadro de Síndrome Vertiginoso'),
('Cuadro de sinositis'),
('Cuadro de Sinusitis'),
('Cuadro de sinusitis y fiebre'),
('Cuadro de TAG (trastorno de ansiedad generalizada)'),
('Cuadro de Vértigo'),
('Cuadro de virosis respiratoria'),
('Cuadro de vómitos y diarrea'),
('Cuadro depresivo con angustia y miedo'),
('Cuadro febril'),
('Cuadro febril agudo'),
('Cuadro febril y dolor de cabeza. Covid 19'),
('Cuadro febril, infección pulmonar'),
('Cuadro gripal'),
('Cuadro gripal (ver)'),
('Cuadro gripal, tos fuerte'),
('Cuadro hepático/ vómitos y diarrea'),
('Cuadro infeccioso “ver certificado”'),
('Cuadro respiratorio viral'),
('Cuadro Viral'),
('Cuadro viral respiratorio'),
('Cuerpo extraño en ojo derecho'),
('Cuerpo extraño en ojo izquierdo'),
('Decaimiento y dolor muscular'),
('Dedo anular derecho fracturado'),
('Dedo anular izquierdo fracturado'),
('Dedo anular izquierdo lesionado'),
('Dedo fracturado'),
('Dedo medio derecho reventado y fracturado'),
('Dedo meñique del pie quebrado'),
('Deficit piramidal derecho'),
('Derrame ocular, diagnóstico ilegible'),
('Descompensación / dolor abdominal'),
('Desgarro inguinal lado derecho'),
('Desgarro muscular'),
('Desgarro muscular gemelar pierna derecha'),
('Desmayo y contusiones en rostro'),
('Diabetes descompensada'),
('Diabetes severa tipo II'),
('Diagnóstico ilegible'),
('Diagnóstico ilegible, dolor en el talón'),
('Diarrea'),
('Disfunciones orgánicas/Aparato cardiovascular en general'),
('Disnea y astenia marcada'),
('Distensión en pierna izquierda'),
('Disuria, infección urinaria'),
('Diverticulitis complicada/cirugía'),
('Dolor abdominal'),
('Dolor abdominal y epigastralgia'),
('Dolor abdominal y vómitos'),
('Dolor abdominal, cálculos renales'),
('Dolor Cervical'),
('Dolor cervical / hombro derecho'),
('Dolor corporal y fiebre'),
('Dolor de cabeza'),
('Dolor de cintura y espalda'),
('Dolor de garganta y fiebre'),
('Dolor de garganta y tos'),
('Dolor de garganta, cabeza y muscular + fiebre'),
('Dolor de muela'),
('Dolor den brazo izquierdo'),
('Dolor dorsal intenso'),
('Dolor en articulación de rodilla derecha'),
('Dolor en bajo vientre y pierna derecha'),
('Dolor en brazo izquierdo, cuello y omóplato'),
('Dolor en el brazo izquierdo y vómitos'),
('Dolor en espalda y pierna'),
('Dolor en hombro'),
('Dolor en hombro (verificar diag.)'),
('Dolor en hombro derecho'),
('Dolor en nervio ciático'),
('Dolor en pecho'),
('Dolor en región inguinal'),
('Dolor en túnel carpiano mano derecha'),
('Dolor en zona rectal'),
('Dolor inguinal / testicular'),
('Dolor inguinal testicular izquierdo'),
('Dolor intestinal / internado en UOM'),
('Dolor Lumbar'),
('Dolor lumbar agudo'),
('Dolor Lumbosacro con irradiación a glúteo'),
('Dolor precordial'),
('Dolores crónicos en la espalda'),
('Dolores en tórax / problemas pulmonares'),
('Dolores musculares /diag. Ilegible'),
('Dolores renales'),
('Enfermedad coronaria'),
('Enteritis + fiebre'),
('Enterocolitis aguda'),
('Entorsis de muñeca izquierda'),
('Entorsis de rodilla derecha'),
('Entorsis de tobillo'),
('Entorsis de tobillo derecho'),
('Entorsis de tobillo izquierdo'),
('Entorsis tobillo izq. y golpe codo izq.'),
('Epicondilitis en codo derecho'),
('Epigastralgia'),
('Epoc reagudizado'),
('Erisipela'),
('Erisipela / fiebre'),
('Erisipela en ambas piernas'),
('Erisipela en pierna derecha'),
('Erisipela en piernas '),
('Erisipela, fiebre y dolor intenso en pierna izq.'),
('Esguince de pulgar derecho'),
('Esguince tobillo derecho'),
('Esguince y torcedura de rodilla derecha'),
('Espuelón en pie'),
('Estado febril'),
('Estado febril / malestar corporal'),
('Estado februl – angina'),
('Estado gripal'),
('Estado gripal (avisó el día 29/11/17)'),
('Estado gripal / dolor de garganta'),
('Estado gripal / fiebre'),
('Estado gripal, problemas respiratorios'),
('Estado gripal. Sinusitis aguda'),
('Estudios auditivos'),
('Estudios cardiológicos'),
('Estudios médicos / fondo de ojos'),
('Estudios médicos en cuello y garganta'),
('Estudios pulmonares'),
('Extracción de pieza dental'),
('Extracción dentaria'),
('Extracción dentaria múltiple'),
('Extracciones dentarias múltiples'),
('Faringitis'),
('Faringitis "a verificar"'),
('Faringoamigdalitis pultácea'),
('Faringotraqueitis'),
('Fiebre alta'),
('Fiebre y decaimiento'),
('Fiebre y dolor de cabeza'),
('Fiebre y dolor de espalda'),
('Fiebre y dolor de garganta'),
('Fiebre y vómitos'),
('Fiebre, congestión y tos'),
('Fiebre, dolor de garganta, estado gripal'),
('Fisura anal aguda (posible cirugía)'),
('Fisura costal izquierda'),
('Fisura de costilla'),
('Flemón agudo'),
('Forúnculo'),
('Forúnculo en glúteo'),
('Fractura de hueso metacarpiano en mano derecha'),
('Fractura de peroné derecho'),
('Fractura de peroné izquierdo'),
('Fractura en mano derecha'),
('Fractura muñeca izq. Y cortes en rostro'),
('Gastritis'),
('Gastritis Aguda'),
('Gastroenteritis'),
('Gastroenteritis / Posibles cálculos renales'),
('Gastroenteritis acompañado de mareos y vómitos'),
('Gastroenteritis aguda'),
('Gastroenterocolitis'),
('Gastroenterocolitis aguda'),
('Golpe de calor'),
('Golpe e infección en codo derecho'),
('Golpe en caja torácica'),
('Golpe en esternón'),
('Golpe en mano derecha, fractura dedo meñique'),
('Golpe en rodilla derecha'),
('Golpes en manos y desgarro intercostal izq.'),
('Golpes en manos y hemitorax, fract. Intercostal izq.'),
('Gonalgia aguda'),
('Gonalgia derecha'),
('Gonalgia en brazo derecho'),
('Gonalgia en rodilla'),
('Gonalgia en rodilla derecha'),
('Gonalgia en rodilla. Cirugía meniscal rodilla derecha'),
('Hemorragia digestiva'),
('Hemorragia nasal'),
('Hemorragias digestivas'),
('Herida cortante en pie izquierdo desde 22/01/22'),
('Hernia de disco / dolor cervical'),
('Hernia Discal L4 – L5'),
('Hernia inguinal'),
('Hernia inguinal izquierda'),
('Hipertensión arterial'),
('Hipertensión arterial / Parálisis facial'),
('Hipertensión arterial “estuvo internado 3 días”'),
('Hisopado por Covid 19'),
('Implante intraocular'),
('Indisposición por fierre'),
('Infarto agudo de miocardio'),
('Infarto agudo de miocardio/derivación'),
('Infección aguda'),
('Infección en pie derecho'),
('Infección en pierna/fiebre/le inyectaron antibióticos'),
('Infección odontológica'),
('Infección respiratoria'),
('Infección urinaria'),
('Inflamación intestinal'),
('Inflamación testicular'),
('Inflamación y úlcera en pierna derecha'),
('Internación por trombosis en pierna derecha'),
('Internado en UOM por problemas respiratorios'),
('Internado por Pre infarto'),
('Intervención por trombosis en pierna derecha'),
('Intervención quirúrgica'),
('Lesión en dedo índice izquierdo'),
('Lesión en dedo pulgar izquierdo del pie'),
('Lesión en hombro der / intervenido quirúrgicamente'),
('Lesión en hombro derecho / cirugía programada'),
('Lesión en manguito rotador'),
('Lesión en mano derecha'),
('Lesión en región clavícula'),
('Lesión en región clavícula/derivado a consulta cirujano'),
('Lesión interna en rodilla derecha'),
('Litiasis coledociana'),
('Litiasis lumbar bilateral'),
('Lumbalgia'),
('Lumbalgia aguda'),
('Lumbalgia por esfuerzo'),
('Lumbalgia por hernia discal lumbar'),
('Lumbociatalgia'),
('Lumbociatalgia / hernia discal'),
('Lumbociatalgia aguda'),
('Lumbociática pierna derecha'),
('Luxación de dedo anular derecho'),
('Luxación de hombro'),
('Malestar general y fiebre'),
('Malestar general, fiebre'),
('Malestar general, vómitos'),
('Malestar/dolor estomacal'),
('Mareos'),
('Mareos e inestabilidad'),
('Mialgias'),
('Mialgias generalizadas y gastroenterocolitis'),
('Migraña'),
('Neumonía'),
('Neumopatía'),
('Omalgia en hombro derecho'),
('Omalgia en hombro derecho (cirugía)'),
('Omálgia en hombro derecho, tendón lesionado'),
('Onicomicosis en uña del pie'),
('Operado de nariz y garganta'),
('Operado de tendón rotuliano / figura diag. Lumbalgia'),
('Orquitis (inflamación testicular)'),
('Orzuelo en ojo derecho'),
('Orzuelo en ojo izquierdo'),
('Otitis'),
('Parálisis facial provocada por un virus'),
('Parálisis radial miembro superior izquierdo'),
('Persiste con Cuadro de virosis respiratoria'),
('Picadura de avispa'),
('Poliartralgia'),
('Polimialgia con fiebre'),
('Politraumatismos'),
('Posible contagio de virus Covid 19'),
('Posible hernia inguinal'),
('Posible infarto'),
('Posible lesión en hombro “ver”'),
('Posible quebradura en mano derecha'),
('Posible trombosis en miembro izquierdo'),
('Positivo contagio Virus Covid 19'),
('Presión arterial'),
('Presión baja'),
('Problemas cardiológicos'),
('Problemas respiratorios'),
('Problemas respiratorios, tos crónica'),
('Reacción alérgica a la medicación (Dipirona) colocada para tratar gastroenteritis'),
('Rehabilitación cuadro de ACV'),
('Rinofaringitis'),
('Riñones irritados / fuertes dolores'),
('Rodilla izquierda, rotura de ligamentos cruzados'),
('Rotura de Ligamento cruzado rodilla izquierda. Cirugía de rodilla izquierda'),
('Rotura de meniscos'),
('Rotura de meniscos (aguarda la intervención)'),
('Rotura de meniscos (será intervenido)'),
('Sangrado estomacal “vómitos”'),
('Secuelas respiratorias de Covid 19'),
('Síndrome coledociano'),
('Síndrome de fatiga post viral'),
('Sindrome de manguito rotatorio en hombro izquierdo'),
('Síndrome gripal'),
('Síndrome vertiginoso'),
('Síndrome Vertiginoso en estudio'),
('Sindrome vertiginoso p pinzamiento a nivel cervical'),
('Síndrome vertiginoso por pinzamiento a nivel cervical'),
('Síndrome vestibular agudo severo'),
('Sinusitis'),
('Sinusopatia crónica (intervención quirúrgica)'),
('Sospecha de Fiebre Hemorrágica'),
('Tapón de cera'),
('TEC (trauma craneoencefálico) sin perdida de conocimiento'),
('Tendinitis en hombro derecho'),
('Tendinitis en hombro izquierdo'),
('Tendinitis hombro izquierdo'),
('Tiña pedis en pie derecho'),
('Tirón en muñeca izquierda'),
('Torcedura muñeca izquierda'),
('Tos / Fiebre'),
('Tos, dolor interno en pecho'),
('Tos, estado gripal'),
('Tratamiento cardiológico'),
('Tratamiento odontológico con anestesia'),
('Tratamiento oftalmológico'),
('Tratamiento Psiquiátrico'),
('Trauma en antebrazo derecho'),
('Traumatismo costal izquierdo'),
('Traumatismo de pierna derecha'),
('Traumatismo en dedo mayor del pie derecho'),
('Traumatismo en dedo meñique izquierdo'),
('Traumatismo en dedo pulgar izquierdo'),
('Traumatismo en mano izquierda'),
('Traumatismo en tórax y miembro superior'),
('Traumatismo hombro y brazo derecho'),
('Traumatismo por caída'),
('Traumatismos en brazo izq. y miembros inferiores'),
('Traumatismos, dolor cervical, fisura en tabique nasal'),
('Trombosis hemorroidal aguda'),
('Ulcera en pie derecho'),
('Úlcera en pierna derecha'),
('Urgencia odontológica'),
('Verruga plantar / realizará un tratamiento'),
('Verruga plantar / realizó un tratamiento'),
('Vértigo y mareos'),
('Virosis respiratoria'),
('Virosis respiratoria / fiebre y vómitos'),
('Vómitos y diarrea');